# Generated by Django 4.1.7 on 2023-02-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_task_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.URLField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment_task_api.customer')),
            ],
        ),
    ]
