# Generated by Django 4.1.7 on 2023-02-25 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_task_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
