# Generated by Django 4.1.7 on 2023-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_task_api', '0003_alter_customer_created_at_alter_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='picture',
            field=models.URLField(max_length=9999),
        ),
    ]
