# Generated by Django 4.1.7 on 2023-02-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_task_api', '0004_alter_customerdetails_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('notes_to_customer', 'Notes to customer')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recruitment_task_api.customer')),
            ],
        ),
    ]
