# Generated by Django 4.1.7 on 2023-02-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_task_api', '0006_alter_customerfile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recruitment_task_api.customer'),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='file',
            field=models.FileField(upload_to='customer_files/'),
        ),
    ]
